name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  working-directory: .
  resource-group: rg-devops-student-fafa
  app-service-name: fafanextjs
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       # Step 1: Checkout repository
      - uses: actions/checkout@v4
      # Step 2: Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      # Step 4: Navigate to correct directory and install dependencies
      - name: Install dependencies and build Next.js app
        run: |          
          npm install
          npm run build          
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone
          ls -R build      
      
      # Step 5: Deploy to Azure Web App
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
         app-name: ${{ env.app-service-name }}
         publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
         slot-name: production
         package: ./build/standalone