name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "fafanextjs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Step 3: Debugging directory structure
      #- name: Debug: Print working directory and files
      #  run: |
      #    pwd
       #   ls -R

      # Step 4: Install dependencies and build
      - name: Install dependencies and build Next.js app
        run: |          
          npm install
          npm run build
          mkdir -p ./build/standalone
          mv ./build/static ./build/standalone/static
          mv ./public ./build/standalone/public

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./POCNextJsOnAZuer/build/standalone
